### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#109]
We need to properly apply the Apache 2 license for each project in `30x` and if you find a repository that is no longer used, please remove it.

**Comment by gbrail** [comment]
I clarified with Jeremy -- this just means:

1) Make sure that there's nothing in here that we don't want to have out there.
2) Make sure that everything has a license.

That's all, and it's a good idea. Thanks!

**Comment by theganyo** [comment]
I guess we'll have to create a new organization then.

**Comment by gbrail** [comment]
No, Scott, no need. We can keep using 30x for the various "edge x" and Gozerian-related projects.

**Comment by theganyo** [comment]
Ok, so the description is just wrong. Got it. So as far as I'm concerned this is done.

**Comment by whitlockjc** [comment]
Description updated.
