### ISSUE TITLE
Review/Fix k8s-routers crash on master nodes

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#113]
`k8s-routers` will not deploy/run on master nodes and will continue crash loop forever.  This will pull the image for each attempt.

**Comment by whitlockjc** [comment]
It seems this is working by design based on what the Kubernetes folks say: https://github.com/kubernetes/kubernetes/issues/29108  Long story short, DaemonSets do not play by the same rules that regular Pods do with respect to  `SchedulingDisabled`.  And with a fix not coming for a while, we should just change to deployments when deploying the k8s-routers.

**Comment by whitlockjc** [comment]
We can work around this using a node selector for the `DaemonSet`: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.3/docs/user-guide/node-selection/index.md

**Comment by whitlockjc** [comment]
It seems node selector has been deprecated: http://kubernetes.io/docs/user-guide/node-selection/

**Comment by whitlockjc** [comment]
I ended up using node affinity because `nodeSelector` does not allow you to say _"Do not run on these nodes"_ and that's what we need.

**Comment by vsimon** [comment]
hi @whitlockjc I'm curious how did you go about it?

I tried adding the following annotation with operator NotIn but it didn't work (in 1.3.4):

```
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "nodeAffinity": {
          "requiredDuringSchedulingIgnoredDuringExecution": {
            "nodeSelectorTerms": [
              {
                "matchExpressions": [
                  {
                    "key": "kubernetes.io/hostname",
                    "operator": "NotIn",
                    "values": ["kubernetes-master"]
                  }
                ]
              }
            ]
          }
        }
      }
```

**Comment by vsimon** [comment]
Ah nevermind, I was trying DaemonSets and DaemonSets don't play by the rules yet w.r.t. these annotations, right?
