### ISSUE TITLE
Define network policy wiring pattern

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#117]
Now that we've got network isolation protoyped and ready to go, we need to design the official pattern for wiring these things together.  Since `NetworkPolicy` objects use label selectors to wire things up, we need to agree upon the label names and values we will use to make this happen.

**Comment by noahdietz** [comment]
We need one label that every `namespace` will contain. This will be used by  the`NetworkPolicy`  `ingress` to filter pod traffic

**Comment by mpnally** [comment]
Can the label be simply `name` and the value is the name of the namespace? Why introduce any new concepts?

**Comment by noahdietz** [comment]
@mpnally sounds good to me
