### ISSUE TITLE
Namespace watcher for network isolation

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#119]
We need a namespace watcher for Kubernetes that will watch for namespace `Added` and `Modified` events and perform the following actions:
1. Make sure the `name` label is set to the name of the namespace _(This is used during network isolation)_
2. Make sure network isolation is enabled/configured _(when necessary)_ by setting the `net.beta.kubernetes.io/network-policy` annotation to be the following JSON document: `{"ingress": {"isolation": "DefaultDeny"}`
3. For namespaces where network isolation is desired, make sure the proper `NetworkPolicy` objects are created:
   1. Disallow Pod<->Pod communication for Pods outside this namespace
   2. Allow Pod<->Pod communication for Pods within this namespace
   3. Allow Pod<->Pod communication for Pods in the `apigee` namespace _(this should probably be a list of namespaces)_ to Pods in this namespace _(We could even make this so that only the necessary pods, like the `k8s-router` Pods, can do this)_

**Comment by whitlockjc** [comment]
In all seriousness, we should probably watch `NetworkPolicy` events as well to make sure that whenever a `NetworkPolicy` we _own_ is altered/deleted that we restore/recreate it.

**Comment by whitlockjc** [comment]
Disregard.  When we implement real `authz`, we can solve this then.  For now, just handle the items in the original description.

**Comment by noahdietz** [comment]
https://github.com/30x/congress/tree/master

**Comment by whitlockjc** [comment]
Feel free to close this issue and assign the `beta` milestone to your new `congress` tasks so they get prioritized properly.
