### ISSUE TITLE
Research gap between Trireme and container solution for Node.js on Edge

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#133]
One of the reasons for Shipyard is to replace the Trireme-based _Node.js on Edge_ with a container-based solution.  While Shipyard already allows you to build/deploy Node.js applications on Kubernetes, there are features that the Trireme-based solution provide that we need to attempt to provide, or make sure they still work, when using the container-based solution.

**Comment by whitlockjc** [comment]
After talking to @gbrail, the main thing that we need to do is make sure that the [apigee-access](https://github.com/apigee/apigee-access) module _(Used for  is used for various features like cache manipulation, variable access, ...)_ works.  There are other features available made available to Node.js running on Trireme but they were for using Java from within Node.js.  If there are any corrections to this, or additions, they will be added to the comments below.

**Comment by whitlockjc** [comment]
@mpnally just brought up a good point that we would be better figuring out what features `apigee-access` provides and see what it would take to enable/use those features using vanilla-node.js.  We never said that node.js applications built for Edge _(Trireme)_ would be able to be redeployed as-is on Kubernetes.

**Comment by mpnally** [comment]
Here is a shoot-from-the-hip reaction to this:
- Access and modify "flow variables" within the Apigee message context.

Does not make sense in a Shipyard context. We will never do this.
- Retrieve sensitive data from the the secure store (AKA "vault").

This makes sense as a remote API. The Edge team needs to expose the API. Someone outside the Edge team could write a Node SDK for it.
- Use the built-in distributed cache.

This makes sense as a remote API. The Edge team needs to expose the API. Someone outside the Edge team could write a Node SDK for it.

*Use the built-in distributed quota service.

This makes sense as a remote API. The Edge team needs to expose the API. Someone outside the Edge team could write a Node SDK for it.

*Use the OAuth service.

This makes sense as a remote API. The Edge team needs to expose the API. Someone outside the Edge team could write a Node SDK for it.
