### ISSUE TITLE
Install key in Edge KVM for corresponding Edge environmnet when Shipyard environment is created.

### ISSUE THREAD

**Issue by mpnally** [30x/project-management#136]
http://docs.apigee.com/api-services/content/environment-keyvalue-maps

**Comment by whitlockjc** [comment]
For Edge integration, we need to manage the `k8s-router` keys so that they are stored in the KVM.  To do this, we have a few options:
1. Have `enrober` do this
2. Have a controller handle this

**Comment by noahdietz** [comment]
we are going with [option 1](https://github.com/30x/enrober/issues/58) for right now (just for the record, @whitlockjc )

**Comment by whitlockjc** [comment]
Makes sense.

**Comment by jbowen93** [comment]
I'll assign this to myself. The corresponding enrober issue is [#58](https://github.com/30x/enrober/issues/58)

**Comment by whitlockjc** [comment]
Once we verify that we can use Dibyo's proxy configuration, we'll close this issue.  I'm pretty sure @jbowen93 has done the work, we just need to verify it works as-is.
