### ISSUE TITLE
Deploy newer version of kubernetes-dashboard

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#142]
We need to deploy a version of kubernetes-dashboard with `Deployment` support.

**Comment by jbowen93** [comment]
Currently we aren't running any version of the kubernetes dashboard. However it's trivial to install it. A simple `kubectl create -f dashboard.yaml --namespace=kube-system` is all that is needed. Just tested on E2E successfully.

**Comment by jbowen93** [comment]
Command is `kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.4.0/src/deploy/kubernetes-dashboard.yaml`
per https://github.com/kubernetes/dashboard/releases

**Comment by jbowen93** [comment]
This is currently running on E2E with release 1.4 of the dashboard. To access it run `kubectl proxy &` to start a proxy in the background. The dashboard should then be accessible at `localhost:8001/ui`. Currently we don't have a good publicly facing endpoint for the cluster that supports basic authn so I feel using `kubectl proxy` is the best choice for the time.

**Comment by jbowen93** [comment]
Moving to done as dashboard v1.4.0 is running on both E2E and Prod.
