### ISSUE TITLE
Implement limits on replicas, memory and CPU

### ISSUE THREAD

**Issue by mpnally** [30x/project-management#148]
We should implement some limits on replicas, memory and CPU for shipyard containers. It is easier to liberalize later than to restrict later, so we should make these stricter rather than more liberal. Here is a strawman suggestion:
- Maximum of 3 shipyard environments per Org
- Maximum of 10 Shipyard deployments per Org
- Maximum of 2 replicas per deployment
- Maximum of 500megs per pod
- Some CPU limit per pod

**Comment by whitlockjc** [comment]
- Managing Compute Resources: http://kubernetes.io/docs/user-guide/compute-resources/
- Pod CPU and memory limits: http://kubernetes.io/docs/admin/limitrange/
- Understanding Resource Quotas: http://kubernetes.io/docs/admin/resourcequota/

**Comment by whitlockjc** [comment]
Closing in favor of #164.
