### ISSUE TITLE
Remove manual ECR support

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#150]
Kubernetes has native support for ECR when running within AWS.  This means we could potentially remove the `30x/secretrefresh` stuff and the controller @jlin21 wrote.  Here are the details: https://github.com/kubernetes/kubernetes/issues/19113

Of course, if we want to allow ECR usage outside of AWS we might want to keep these things but I just learned this and it makes sense to see what it offers us.

**Comment by whitlockjc** [comment]
It also seems the ECR documentation has some details on this.  Here are some of those docs:

```
Kubernetes has native support for the AWS EC2 Container Registry, when nodes are AWS EC2 instances.
Simply use the full image name (e.g. ACCOUNT.dkr.ecr.REGION.amazonaws.com/imagename:tag) in the Pod definition.
All users of the cluster who can create pods will be able to run pods that use any of the images in the ECR registry.
The kubelet will fetch and periodically refresh ECR credentials. It needs the following permissions to do this:
ecr:GetAuthorizationToken
ecr:BatchCheckLayerAvailability
ecr:GetDownloadUrlForLayer
ecr:GetRepositoryPolicy
ecr:DescribeRepositories
ecr:ListImages
ecr:BatchGetImage
Requirements:
You must be using kubelet version v1.2.0 or newer. (e.g. run /usr/bin/kubelet --version=true).
Your nodes must be in the same region as the registry you are using
ECR must be offered in your region
```

**Comment by whitlockjc** [comment]
Minions need IAM roles similar to this:

``` json
{
      "Effect": "Allow",
      "Action": [
        "ecr:GetAuthorizationToken",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        "ecr:GetRepositoryPolicy",
        "ecr:DescribeRepositories",
        "ecr:ListImages",
        "ecr:BatchGetImage"
      ],
      "Resource": "*"
    }
```

**Comment by noahdietz** [comment]
@whitlockjc is this something we still want? Do we want it for GA? This solution seems a little easier to add/maintain than #144

**Comment by whitlockjc** [comment]
I like this approach.  Maybe we can get @jlin21 to help out.

**Comment by jlin21** [comment]
Sounds like something fun to try

**Comment by noahdietz** [comment]
@whitlockjc @madhurranjan I don't think this solves our problem of needing to refresh the ECR secrets for `kiln`.

These look to be "read" only actions that the `kubelet` needs to pull images from ECR when specified in the PTS. `kiln` needs to push images into ECR. Also, the credentials need to be placed in the "correct" spot (idk what this is yet, we have created them all ourselves with secrets thus far), which I don't think the `kubelet` supports, I think it keeps them for itself.

Most of the references[ in the docs](http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry) also mention that these are `read` commands and "you just need read privileges".

Thoughts?

**Comment by whitlockjc** [comment]
I think this would work for pulling images from ECR but `kiln` also needs to interact with ECR and the native ECR support doesn't help with that.  After re-reading the docs, I do think we could consult the `aws-ecr-key` `Secret` and monitor that via the sidecar and have it kill the `Pod` whenever the secret changes.

**Comment by madhurranjan** [comment]
Killing the pod might be a bit of a drastic change . If ECR is down at the moment you kill it , you bring everything down. Lets go with whatever you're doing right now. Yes , ecr integration just helps with pulling the image but not pushing it to ECR. Apologies for the confusion

**Comment by whitlockjc** [comment]
That's how it's working already.  :)  The current `kiln` process uses a sidecar to kill the `Pod` on a timer.

**Comment by noahdietz** [comment]
But since Mamu added this integration, I think we can close the issue.

We will keep what we have now, but I will look to see if there is any fat I can trim from `kiln` regarding imagePullSecrets, now that we don't need them.

Thanks!

**Comment by whitlockjc** [comment]
I agree.  Seeing that this doesn't impact `kiln` right now, we're good.  We _could_ had updated `kiln` to mount the same secret that ECR uses and use a filesystem watch to update the internal ECR credentials when Kubernetes updates the secret on disk but if it ain't broke...
