### ISSUE TITLE
Update Shipyard documentation for node version support

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#169]
Shipyard was updated to support the user requesting a Node.js version when building an image.  We need to update the Shipyard documentation to reflect these changes.

Long story short, there is a new `shipyardctl create image` option _(`--node-version`)_ that allows you to specify the `mhart/alpine-node` tag to use for the base of your Docker image.  There are two things we need to document beyond the existence of the new option:
1. The option is _optional_ and defaults to `4` _(The latest Node.js `v4.x` release)_
2. The option value must match one of the available Docker image tags listed here: https://hub.docker.com/r/mhart/alpine-node/tags/

**Comment by WWitman** [comment]
See the doc here and search on node-version and nodeVersion for details: https://docs.google.com/document/d/1MhqKVz6qBW0rZjvvseNgVn589rnOaGxbO4KoEFDHLTE/edit#

**Comment by noahdietz** [comment]
lgtm

**Comment by whitlockjc** [comment]
Shipped.
