### ISSUE TITLE
Document Node image build details

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#173]
We should document the steps taken by our Node.js Docker image build process.  This could be useful information, like leveraging this knowledge to interact with a private NPM server.  In fact, we should use that case in the documentation as an explicit example.

**Comment by noahdietz** [comment]
appears in @WWitman 's latest doc draft for beta3/GA. Can close this now.

**Comment by noahdietz** [comment]
rather, the nodeVersion parameter is documented. not so much all of the details on node build environment within kiln. still need a section on that

**Comment by WWitman** [comment]
I'm unclear what's needed here.  @noahdietz  or @whitlockjc can you give more details? Or we can chat next week.

**Comment by whitlockjc** [comment]
I will give you an example tomorrow.  Ping me if you've not seen an update.  Long story short, I think it makes sense to describe _what happens_ behind the scenes.

**Comment by whitlockjc** [comment]
### Docker Image Process

When turning your _.zip_ file into a Docker image, we build on top of the [mhart/alpine-node](https://hub.docker.com/r/mhart/alpine-node/) image.  When we get your _.zip_, the following are the series of steps we run to produce the Docker image:
1. Unzip your _.zip_
2. Copy everything in the_.zip_ into the image
3. We run `npm install` to install your dependencies
4. We set the image `CMD` to `npm start`

The reason knowing this could be important is because now you know the contract required by Shipyard **and** knowing this could help you in the event you have some special packaging requirements.  Examples:
- Reading the above tells me that I can omit `node_modules` from my _.zip_ because the image build process will take care of it for me.  _(This means much quicker uploads to Shipyard.)_
- I now know that if I need to package custom or private Node.js modules, I can include those in my `node_modules` and the `npm install` step will install the other dependencies
- I can include a `.npmrc` in my _.zip_ root and use this to customize the NPM interactions, like consuming a private NPM server

**Comment by whitlockjc** [comment]
@WWitman Above is an example of the extra information that we could/should include in the Shipyard Guide.  The idea is to give the consumer a better idea of the required contract **and** to provide them with enough information to handle special cases like custom Node.js modules, interacting with private NPM servers, etc.
