### ISSUE TITLE
Discuss Apigee as the source of truth for Kubernetes

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#189]
As we begin to build a more Apigee-centric Shipyard, we are facing a problem with treating Apigee as the source of truth.  The way it stands now, Shipyard interacts with Apigee APIs via user-triggered actions.  The benefit of this is that when an Apigee API is consumed, it is consumed as the user and the actions are authenticated/authorized accordingly.  So when a user creates a Shipyard environment, the Apigee KVM API call(s) to create/update KVM values for the Shipyard routing keys are made as the same user creating the Shipyard environment.

The problem is that as we try to do more automatic integration between Apigee and Shipyard, we cannot rely on user-triggered actions which means we need a better way to create non-user services that will be scoped appropriately to securely interact with Apigee from Kubernetes.  The more design work we do for Shipyard based on the SJC meetings, the more this problem is becoming more apparent.

We need to discuss how we want to solve this problem.  The major topics we need to address _(not guaranteed to be complete)_:

* Which model _(pull or push)_ do we use? _(Each have cons/pros.)_
* What mechanism do we want to use for allowing these Kubernetes services to use for authenticating to Apigee?
* What scoping do we need for our Kubernetes controller(s) doing this?  _(We could go with a single, cluster-wide approach or we could go with a per-environment/namespace model.  Each have cons/pros.)_
* What is the interval at which these controller(s) attempt to hit Apigee APIs?

**Comment by whitlockjc** [comment]
My proposal for **now** is that we do the following:

* Where possible, let Shipyard API interactions trigger the automatic syncing of Apigee information into Kubernetes _(For example, create/update of a deployment will sync the configuration stored in the KVM into Kubernetes)_
* Where not possible, we have create a new Shipyard API to force the synchronization of the Apigee information into Kubernetes
* ~~For hosts, we still need to allow the Shipyard API user to specify hosts because of a deployment needing a proxy to know which hosts to use for the routing for that deployment~~ _(Apigee Edge will be consulted for hosts and passing extra hosts, or working in a non-Apigee approach will not work)_

This will let us move forward now and while it's not automatic, at least users have a way to self-fix issues where there is a sync issue.  It also means we can spend more time working out a _real_ solution to running controllers in Kubernetes that are tied to properly scoped permissions.

**Comment by mpnally** [comment]
I agree with the first 2 points, although I hope the second is unnecessary. I didn't understand the third.

**Comment by whitlockjc** [comment]
These were features for the short term, the MVP that could get us working on this now without solving the infrastructure needs of the long term pass.  We'll talk in standup.

**Comment by AdamMagaluk** [comment]
@whitlockjc Could you elaborate on point three, i feel like i'm missing something.

**Comment by whitlockjc** [comment]
I was just saying that we could/should allow the Shipyard user to provide hosts information instead of pulling it solely from Apigee Edge.  The idea was to still allow Shipyard to work without Apigee Edge integration for this but I don't think this is necessary as we're not writing a generic tool anymore.
