### ISSUE TITLE
Given a Deployment, deploy it to k8s

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#19]

**Comment by jbowen93** [comment]
Namespaces are created based on ImageDeployment.Repo field.

**Comment by jbowen93** [comment]
Replication Controllers are created based on ImageDeployment object. Image to be used is a concatenation of `repo`, `application` and `revision` fields.

**Comment by jbowen93** [comment]
Moved from using Replication Controllers to using Deployments.
