### ISSUE TITLE
Write up 'apigeectl' cli document

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#25]
What should the experience be so that I can have local k8s cluster running that ultimately has Apigee Gateway.

**Comment by prabhatjha** [comment]
CLI should make it easier to do some of https://docs.google.com/document/d/1QIlI0pRgw5E15hPTpdJmtcwNlGa2l_GVJijZsIlwFww/edit

**Comment by jbowen93** [comment]
Not confident this is a wholly necessary task. `kubectl` provides a lot of functionality out of the box. Would like to discuss what specific things we want from a CLI that isn't being provided by `kubectl`.
