### ISSUE TITLE
move config for agent to edge-micro

### ISSUE THREAD

**Issue by shawnfeldman** [30x/project-management#34]

**Comment by prabhatjha** [comment]
I will add that move config related to Edge to edge_config. For example, managementUri, vaultName etc all should go under edge_config. So we have two configs: edge_config and edgemicro

**Comment by shawnfeldman** [comment]
ok so I think, we should split current config/default.yaml into two: default-edge-wiring.yaml and default-edgemicro-config.yaml  ( if you have better name then let me know). Now when I do ~/.edgemicro configure, it combines properties of two files and creates ~/.edgemicro/config.yaml

**Comment by shawnfeldman** [comment]
actually, the one  you put in ~/.edgemicro, does not need to know about authUri, baeUri etc so why even have that there in generated one.
