### ISSUE TITLE
Write design doc for Ingress multi-tenant

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#45]
Ingress would have to check that host headers are valid for given namespace. When namespace is created (Deployment API), there should be an API to do CRUD of valid host headers.

**Comment by whitlockjc** [comment]
The current ingress, which is already documented, will only change by validating via an API Key.  So with this being the only change, I don't see a whole new document when the [current document](https://github.com/30x/k8s-pods-ingress/blob/master/README.md) already describes things pretty well.  Once we support the API Key, which is a subtask of https://github.com/30x/k8s-pods-ingress/issues/11, the documentation will be updated with the necessary documentation on how to use it.

Does this help?

**Comment by prabhatjha** [comment]
This is now done.
