### ISSUE TITLE
Create a demo postman script

### ISSUE THREAD

**Issue by tnine** [30x/project-management#50]
We need a demo script for our next demo.  It should accomplish the following.
- [ ] Create an application by uploading a valid zip file. @whitlockjc I'll need a pointer to your echo node app
- [ ] Create and upload the pod template spec for the image
- [ ] Deploy the application with a secret and the given pod template spec
- [ ] Hit the api without the secret header to prove the request is rejected
- [ ] Hit the api with the secret to prove the traffic is allowed

**Comment by prabhatjha** [comment]
Here is what script should do:
1. Create environment with with a secret/apiKey using Josh's API
2. Upload a Node.js app using build API (Todd's API)
3. Create a deployment in environment created on 1 with image from #2 with and pre-defined host header 
4. Create a proxy on Edge that calls the deployed app by setting secret from 1 in header and right host header.
5. Test hitting #4 works.
6. Test that shows that hitting API without apiKey and wrong host header don't work.
7. Change Node.js source app, redeploy and show 5&6 again.

Obviously, as new deployment is made with apiKey and host header, ingress is doing its thing to regenerate configuration. [Jeremey]
