### ISSUE TITLE
refactor edgemicro configurator

### ISSUE THREAD

**Issue by theganyo** [30x/project-management#7]
edgemicro configuration should be able to be run independently from starting microgateway. Likewise, microgateway should not expect any communication from the agent for its operation and should start standalone.

**Comment by prabhatjha** [comment]
Pls coordinate with Scott on this. This will allow us to make progress on #10 in parallel

**Comment by prabhatjha** [comment]
Separate code that gets config from Edge from agent's functionality of monitoring gateway - restarting and other apis like cpu use etc
