### ISSUE TITLE
Shipyard use case requires a boilerplate PTS to be created from an image.

### ISSUE THREAD

**Issue by jbowen93** [30x/project-management#76]

**Comment by jbowen93** [comment]
@tnine We should work together on this since it's part of the build pipeline.

**Comment by prabhatjha** [comment]
This should be done by build API which gives client/end-user a PTS URL to use during deployment. Assigning it to Todd.

**Comment by prabhatjha** [comment]
Josh, pls ping Martin when you are back. We have discussed a simple impl for alpha.

**Comment by tnine** [comment]
Create an endpoint that allows us to generate a default pod template spec.  To do this, we should return a following link in the body of the build process.

GET /beeswax/images/api/v1/defaultpts?image=[absolute image URI]
