### ISSUE TITLE
Update end user script for Shipyard Alpha

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#80]
Pls update doc at https://docs.google.com/document/d/1zupDMK2OuKg3O3109Essqe_3AU8qS1ic2XdAJkza06k/edit#

**Comment by WWitman** [comment]
This is the new alpha script doc link:

https://docs.google.com/a/apigee.com/document/d/1Ql3_xyuoMv81_0D98mfWaWBeQ_RZHK3KNtAWHe7Ozqs/edit?usp=sharing
