### ISSUE TITLE
Get nginx logs to k8s logging server

### ISSUE THREAD

**Issue by prabhatjha** [30x/project-management#81]

**Comment by prabhatjha** [comment]
Mamu and co has Elasticsearch/kibana for log where all logs go to. This task was to verify that nginx logs are indeed showing up there so that we can see lots without using kubectl. We need to do the same for other components - build and deploy.

**Comment by whitlockjc** [comment]
The nginx logs are in `/var/log/nginx/[access|error].log`.  To consume these files, someone will need to pull these down as the Ingress Controllers themselves do not print their logs to stderr/stdout.

**Comment by whitlockjc** [comment]
This has been fixed on e2e and production.  Logs are being written to `/var/log/nginx/k8s-[private|public]`.

**Comment by whitlockjc** [comment]
Assigning to @madhurranjan to verify the logs are being written and to wire up whatever logging systems to use these logs.

**Comment by whitlockjc** [comment]
Logs are working, I tested.  Assigning to @jlin21 to make sure these get hooked into our logging system.
