### ISSUE TITLE
As a workaround in K8S 1.2, we need to explicitly create a Calico rule for each pod to allow the Ingress to send requests to them

### ISSUE THREAD

**Issue by mpnally** [30x/project-management#85]
In K8S 1.3, we will be able to ensure that the ingress can send requests to Pods by adding a network rule to the PTS. This rule will reference the namespace and label of the ingress.

Unfortunately, for K8S 1.2, we will have to implement a workaround. A specific calico rule will have to be created for each pod. The obvious place to do this is in the ingress "configurator", since that is the only software that actually sees the pods (other than Nginx itself).

**Comment by whitlockjc** [comment]
Do you have any links to where I can get up to speed on this?

**Comment by mpnally** [comment]
Update—for the alpha, we will simply turn off namespace isolation for the pods
