### ISSUE TITLE
Do not allow privileged containers to be specified in PTS

### ISSUE THREAD

**Issue by mpnally** [30x/project-management#86]
K8S allows something like this in a PTS:
                        "securityContext": {
                                               "privileged": true
                       },
We need to disallow this for customer containers

**Comment by jbowen93** [comment]
For the time being I'm going to create an environment variable `ALLOW_PRIV_CONTAINERS`. If this is set to `"false"` then enrober will modify any privileged values to be false. We may need to revisit this issue in the future.
