### ISSUE TITLE
Move from label.app to label.component

### ISSUE THREAD

**Issue by jbowen93** [30x/project-management#88]
We should be strict in our yaml files to use a `component` label as opposed to `app` since it is clearer.

Example:

```
metadata:
  labels:
    app: enrober
```

would become

```
metadata:
  labels:
    component: enrober
```

**Comment by whitlockjc** [comment]
Works for me.  The Kubernetes documentation used `app` so I think that's how we got into this situation.

**Comment by jbowen93** [comment]
I'll deploy a v0.1.7 version of enrober that expects this convention on given pod template specs.

**Comment by tnine** [comment]
Done in shipyard v0.1.9.  It's now in e2e for testing.

**Comment by tnine** [comment]
v0.1.9 when out to prod, it's not in v0.1.10
