### ISSUE TITLE
Review API Design

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#90]
Both enrober and shipyard have tasks to refactor their APIs to be more RESTful and consistent.  We need to review the APIs as a team and make any remaining suggestions for enrober/shipyard API changes.

**Comment by jbowen93** [comment]
Should we schedule a time to discuss this as a group before we move forward with the individual refactorings?

**Comment by whitlockjc** [comment]
I think that's a great idea.  I'll let @mpnally lead that.
