### ISSUE TITLE
Automate/Document creating a suitable Edge Proxy

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#91]
Once a Node.js application is deployed via Shipyard _(enrober)_, the end user needs to create a suitable Edge Proxy.  We need to document how to create this Edge Proxy from scratch and then look into a way to automate the creation of one based on some script or what not.

**Comment by noahdietz** [comment]
This might become automated in [shipyardctl](https://github.com/30x/shipyardctl/issues/4)
