### ISSUE TITLE
Research using kubectl in a secure manner

### ISSUE THREAD

**Issue by whitlockjc** [30x/project-management#97]
`kubectl` is the main interface for k8s and most people learning/using k8s will know this tool.  Instead of wrapping all the k8s APIs or providing yet another CLI wrapper, we should first consider what options we have to providing access to k8s via the API and `kubectl` such that we do not have to create/maintain a compatibility layer yet we allow user-based and role-based access control to k8s.  I know @jbowen93 has looked into this some but here are a few ideas _(Feel free to share if you have more)_:
- Use k8s ABAC/RBAC in a way that uses Apigee's user/role management
- Write a simple pass-through proxy that sits in front of the k8s API that uses Apigee's user/role management there

**Comment by tnine** [comment]
What about an auth CLI that we create ourselves.  For instance, when using amazon ECR I invoke the following command. 

`aws ecr get-login --region us-east-1`

This then prints out the following

`docker login -u AWS -p [GENERATED PASSWORD] -e none [ENDPOINT]`

We could do something similar, such as a login cli using our credentials.  This would then return a command or a set of commands that could be executed and allow users to modify their config and log in.  For instance, something like.

`kubectl config set-cluster <etc>`

On the server side, this would correctly create or update a user with access to the namespaces they should be allowed to administer.

Thoughts?

**Comment by whitlockjc** [comment]
Useful resources for this spike:
- https://github.com/kubernetes/kubernetes/blob/master/docs/design/access.md
- http://kubernetes.io/docs/admin/accessing-the-api/

**Comment by whitlockjc** [comment]
We've proven it's possible, now we just need to implement this.

http://apigee.com/about/blog/engineering/kubernetes-authentication-enterprise

**Comment by mpnally** [comment]
To use kubectl instead of enrober, we need user authentication via SSO (solution described above) and access control using our permissions service. Our permissions service needs access to the request, including the body—for example, the details of the namespace or deployment being created—in order to make a decision. Just knowing the command is not enough.

**Comment by whitlockjc** [comment]
We got it handled.  We're documenting the tasks required for this.  :)
